-- Click tracking and shortlinks schema
-- This enables tracking of deal clicks and branded shortlinks

-- Deal destinations table for shortlinks
CREATE TABLE IF NOT EXISTS deal_links (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug TEXT UNIQUE NOT NULL,           -- e.g., 'custoq'
  target_url TEXT NOT NULL,            -- e.g., https://custoq.com/pricing?coupon=ISD70
  deal_id UUID,                        -- optional FK to deals table
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- Optional metadata
  title TEXT,                          -- human readable title
  description TEXT,                    -- optional description
  is_active BOOLEAN DEFAULT TRUE,      -- allow disabling links
  
  CONSTRAINT fk_deal_links_deal_id FOREIGN KEY (deal_id) REFERENCES deals(id) ON DELETE CASCADE
);

-- Click events table
CREATE TABLE IF NOT EXISTS deal_clicks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL,
  utm_source TEXT,
  utm_medium TEXT, 
  utm_campaign TEXT,
  utm_content TEXT,
  referer TEXT,
  user_agent TEXT,
  ip_hash TEXT,                        -- hashed for privacy
  country TEXT,                        -- geo data
  city TEXT,                           -- optional city data
  device_type TEXT,                    -- mobile/desktop/tablet
  browser TEXT,                        -- chrome/firefox/safari etc
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_deal_clicks_slug_created_at ON deal_clicks (slug, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_deal_clicks_created_at ON deal_clicks (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_deal_clicks_utm_source ON deal_clicks (utm_source);
CREATE INDEX IF NOT EXISTS idx_deal_links_slug ON deal_links (slug);
CREATE INDEX IF NOT EXISTS idx_deal_links_deal_id ON deal_links (deal_id);

-- RLS (Row Level Security) policies
ALTER TABLE deal_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE deal_clicks ENABLE ROW LEVEL SECURITY;

-- Public read access for deal_links (needed for /go redirects)
CREATE POLICY "deal_links_public_read" ON deal_links
  FOR SELECT USING (is_active = TRUE);

-- Admin only write access for deal_links
CREATE POLICY "deal_links_admin_write" ON deal_links
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM profiles 
      WHERE profiles.id = auth.uid() 
      AND profiles.role IN ('admin', 'super_admin')
    )
  );

-- Public insert access for deal_clicks (needed for tracking)
CREATE POLICY "deal_clicks_public_insert" ON deal_clicks
  FOR INSERT WITH CHECK (TRUE);

-- Admin read access for analytics
CREATE POLICY "deal_clicks_admin_read" ON deal_clicks
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM profiles 
      WHERE profiles.id = auth.uid() 
      AND profiles.role IN ('admin', 'super_admin')
    )
  );

-- Founder read access for their own deal clicks
CREATE POLICY "deal_clicks_founder_read" ON deal_clicks
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM deal_links dl
      JOIN deals d ON d.id = dl.deal_id
      JOIN profiles p ON p.id = d.founder_id
      WHERE dl.slug = deal_clicks.slug
      AND p.id = auth.uid()
    )
  );